"""Ollama local AI analyst integration client with fallback support."""

from typing import Any, Dict, List, Optional
import httpx

from app.ai.prompts import PromptBuilder
from app.core.config import settings
from app.core.logging import logger


class OllamaAnalyst:
    """Interfaces with local Ollama LLM provider to synthesize defensive intelligence."""

    def __init__(self) -> None:
        self.base_url = settings.OLLAMA_BASE_URL.rstrip("/")
        self.model = settings.OLLAMA_MODEL
        self.timeout = settings.OLLAMA_TIMEOUT_SECONDS

    async def health_check(self) -> bool:
        """Verifies if Ollama server is running and reachable."""
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                res = await client.get(f"{self.base_url}/api/tags")
                return res.status_code == 200
        except Exception:
            return False

    async def analyze_investigation(
        self,
        target: str,
        target_type: str,
        entities: List[Dict[str, Any]],
        relationships: List[Dict[str, Any]],
        findings: List[Dict[str, Any]],
        risk_score: float,
    ) -> Dict[str, Any]:
        """Generates evidence-grounded AI analysis via Ollama (or deterministic fallback)."""
        prompt = PromptBuilder.build_investigation_analysis_prompt(
            target=target,
            target_type=target_type,
            entities=entities,
            relationships=relationships,
            findings=findings,
            risk_score=risk_score,
        )

        is_available = await self.health_check()
        if not is_available:
            logger.info("Ollama is not running at %s; returning structured defensive baseline analysis.", self.base_url)
            return self._build_deterministic_analysis(
                target=target,
                entities=entities,
                relationships=relationships,
                findings=findings,
                risk_score=risk_score,
            )

        try:
            async with httpx.AsyncClient(timeout=float(self.timeout)) as client:
                res = await client.post(
                    f"{self.base_url}/api/generate",
                    json={
                        "model": self.model,
                        "prompt": prompt,
                        "system": PromptBuilder.SYSTEM_PROMPT,
                        "stream": False,
                    },
                )
                if res.status_code == 200:
                    ai_response = res.json().get("response", "")
                    return {
                        "provider": "ollama",
                        "model": self.model,
                        "analysis": ai_response,
                        "is_fallback": False,
                    }
        except Exception as exc:
            logger.warning("Ollama generation query failed: %s", str(exc))

        return self._build_deterministic_analysis(
            target=target,
            entities=entities,
            relationships=relationships,
            findings=findings,
            risk_score=risk_score,
        )

    def _build_deterministic_analysis(
        self,
        target: str,
        entities: List[Dict[str, Any]],
        relationships: List[Dict[str, Any]],
        findings: List[Dict[str, Any]],
        risk_score: float,
    ) -> Dict[str, Any]:
        """Deterministic, hallucination-free defensive summary used as default/fallback."""
        high_sev = [f for f in findings if f.get("severity") in ("CRITICAL", "HIGH")]

        summary = f"### Defensive Assessment for {target}\n\n"
        summary += f"**[OBSERVED EVIDENCE]**\n"
        summary += f"- Discovered {len(entities)} unique assets and identities across independent OSINT sources.\n"
        summary += f"- Total findings recorded: {len(findings)} (High/Critical: {len(high_sev)}).\n"
        summary += f"- Evaluated OSINT-X Exposure Risk Score: **{risk_score}/100**.\n\n"

        summary += f"**[INFERRED RELATIONSHIPS]**\n"
        summary += f"- Correlated {len(relationships)} explainable relationships linking subdomains, IP infrastructure, and identity footprints.\n\n"

        summary += f"**[DEFENSIVE REMEDIATION]**\n"
        summary += "- Audit all discovered internet-facing subdomains and exposed services.\n"
        summary += "- Ensure MFA enforcement on all digital accounts identified in public registrations.\n"
        summary += "- Schedule continuous asset monitoring to detect drift.\n\n"
        summary += "*Note: Generated by OSINT-X Defensive Engine (Local Ollama offline mode active).*"

        return {
            "provider": "osintx_rule_engine",
            "model": "deterministic_rule_engine",
            "analysis": summary,
            "is_fallback": True,
        }


ollama_analyst = OllamaAnalyst()
